name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Zip integration
        run: |
          cd custom_components
          zip -r ../horaco_switch.zip horaco_switch/
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: horaco_switch.zip
          generate_release_notes: true
